name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ["14", "16", "18"]
        vite: ["2", "3", "4", "5.1", "5.2", "5"]
    name: Node.js ${{ matrix.node }} + Vite ${{ matrix.vite }} on ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Install specified version of Vite
        run: npm install vite@^${{ matrix.vite }}

      - name: Run tests
        run: npm test